# Generated by Django 4.0 on 2022-03-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(default='', max_length=500)),
                ('if_anonymous', models.BooleanField(default=False)),
                ('comment_time', models.TimeField(default=None)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikedComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_time', models.TimeField(auto_now_add=True)),
                ('page_coordinates_x', models.IntegerField(default=None)),
                ('page_coordinates_y', models.IntegerField(default=None)),
                ('rotation_angle', models.IntegerField(default=0)),
                ('picture_url', models.URLField()),
                ('background_url', models.URLField()),
                ('if_anonymous', models.BooleanField(default=False)),
                ('latest_ActTime', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
                ('Real_name_authentication', models.BooleanField(default=False)),
                ('Student_id', models.IntegerField(default=0)),
                ('user_permissions', models.CharField(max_length=20)),
                ('show_yourself', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
