# Generated by Django 4.0 on 2022-03-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('comment_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'commented_posts',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('if_anonymous', models.BooleanField()),
                ('post_id', models.IntegerField()),
                ('like_number', models.IntegerField()),
                ('comment_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='LikedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('like_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'liked_posts',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_time', models.CharField(max_length=50)),
                ('page_coordinates', models.CharField(max_length=50)),
                ('rotation_angle', models.IntegerField()),
                ('picture_url', models.CharField(max_length=50)),
                ('background_url', models.CharField(max_length=50)),
                ('like_number', models.IntegerField()),
                ('comment_number', models.IntegerField()),
                ('if_anonymous', models.BooleanField()),
                ('post_user_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=20)),
                ('Real_name_authentication', models.BooleanField()),
                ('user_permissions', models.CharField(max_length=20)),
                ('show_yourself', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
