# Generated by Django 3.2.5 on 2022-03-23 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=20)),
                ('image_url', models.URLField(max_length=20)),
                ('Real_name_authentication', models.BooleanField(default=False)),
                ('Student_id', models.IntegerField(default=0)),
                ('user_permissions', models.CharField(max_length=20)),
                ('show_yourself', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_time', models.TimeField()),
                ('page_coordinates', models.CharField(max_length=50)),
                ('rotation_angle', models.IntegerField(default=0)),
                ('picture_url', models.URLField(max_length=50)),
                ('background_url', models.URLField(max_length=50)),
                ('if_anonymous', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(default='', max_length=500)),
                ('if_anonymous', models.BooleanField(default=False)),
                ('like_number', models.IntegerField()),
                ('comment_time', models.TimeField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.posts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='LikedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_time', models.TimeField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.posts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'unique_together': {('post_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='CommentedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.TimeField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.posts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'unique_together': {('post_id', 'user_id')},
            },
        ),
    ]
