# Generated by Django 4.0 on 2022-06-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='code_hash',
            field=models.CharField(max_length=100),
        ),
    ]
